/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as StatisticsDataRouteImport } from './routes/statistics-data'
import { Route as StadiumsRouteImport } from './routes/stadiums'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LiveRouteImport } from './routes/live'
import { Route as KnockoutRouteImport } from './routes/knockout'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as FixturesRouteImport } from './routes/fixtures'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamsCodeRouteImport } from './routes/teams.$code'
import { Route as StadiumsSlugRouteImport } from './routes/stadiums_.$slug'
import { Route as NewsReadRouteImport } from './routes/news.read'
import { Route as MatchIdRouteImport } from './routes/match.$id'
import { Route as HistoryYearRouteImport } from './routes/history_.$year'
import { Route as GroupsLetterRouteImport } from './routes/groups.$letter'
import { Route as ApiPublicTrackVisitRouteImport } from './routes/api/public/track-visit'
import { Route as ApiPublicHooksSyncLiveRouteImport } from './routes/api/public/hooks.sync-live'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsDataRoute = StatisticsDataRouteImport.update({
  id: '/statistics-data',
  path: '/statistics-data',
  getParentRoute: () => rootRouteImport,
} as any)
const StadiumsRoute = StadiumsRouteImport.update({
  id: '/stadiums',
  path: '/stadiums',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const KnockoutRoute = KnockoutRouteImport.update({
  id: '/knockout',
  path: '/knockout',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const FixturesRoute = FixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsCodeRoute = TeamsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => TeamsRoute,
} as any)
const StadiumsSlugRoute = StadiumsSlugRouteImport.update({
  id: '/stadiums_/$slug',
  path: '/stadiums/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsReadRoute = NewsReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => NewsRoute,
} as any)
const MatchIdRoute = MatchIdRouteImport.update({
  id: '/match/$id',
  path: '/match/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryYearRoute = HistoryYearRouteImport.update({
  id: '/history_/$year',
  path: '/history/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsLetterRoute = GroupsLetterRouteImport.update({
  id: '/$letter',
  path: '/$letter',
  getParentRoute: () => GroupsRoute,
} as any)
const ApiPublicTrackVisitRoute = ApiPublicTrackVisitRouteImport.update({
  id: '/api/public/track-visit',
  path: '/api/public/track-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksSyncLiveRoute = ApiPublicHooksSyncLiveRouteImport.update({
  id: '/api/public/hooks/sync-live',
  path: '/api/public/hooks/sync-live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fixtures': typeof FixturesRoute
  '/groups': typeof GroupsRouteWithChildren
  '/history': typeof HistoryRoute
  '/knockout': typeof KnockoutRoute
  '/live': typeof LiveRoute
  '/news': typeof NewsRouteWithChildren
  '/players': typeof PlayersRoute
  '/records': typeof RecordsRoute
  '/search': typeof SearchRoute
  '/simulator': typeof SimulatorRoute
  '/stadiums': typeof StadiumsRoute
  '/statistics-data': typeof StatisticsDataRoute
  '/teams': typeof TeamsRouteWithChildren
  '/groups/$letter': typeof GroupsLetterRoute
  '/history/$year': typeof HistoryYearRoute
  '/match/$id': typeof MatchIdRoute
  '/news/read': typeof NewsReadRoute
  '/stadiums/$slug': typeof StadiumsSlugRoute
  '/teams/$code': typeof TeamsCodeRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
  '/api/public/hooks/sync-live': typeof ApiPublicHooksSyncLiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fixtures': typeof FixturesRoute
  '/groups': typeof GroupsRouteWithChildren
  '/history': typeof HistoryRoute
  '/knockout': typeof KnockoutRoute
  '/live': typeof LiveRoute
  '/news': typeof NewsRouteWithChildren
  '/players': typeof PlayersRoute
  '/records': typeof RecordsRoute
  '/search': typeof SearchRoute
  '/simulator': typeof SimulatorRoute
  '/stadiums': typeof StadiumsRoute
  '/statistics-data': typeof StatisticsDataRoute
  '/teams': typeof TeamsRouteWithChildren
  '/groups/$letter': typeof GroupsLetterRoute
  '/history/$year': typeof HistoryYearRoute
  '/match/$id': typeof MatchIdRoute
  '/news/read': typeof NewsReadRoute
  '/stadiums/$slug': typeof StadiumsSlugRoute
  '/teams/$code': typeof TeamsCodeRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
  '/api/public/hooks/sync-live': typeof ApiPublicHooksSyncLiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fixtures': typeof FixturesRoute
  '/groups': typeof GroupsRouteWithChildren
  '/history': typeof HistoryRoute
  '/knockout': typeof KnockoutRoute
  '/live': typeof LiveRoute
  '/news': typeof NewsRouteWithChildren
  '/players': typeof PlayersRoute
  '/records': typeof RecordsRoute
  '/search': typeof SearchRoute
  '/simulator': typeof SimulatorRoute
  '/stadiums': typeof StadiumsRoute
  '/statistics-data': typeof StatisticsDataRoute
  '/teams': typeof TeamsRouteWithChildren
  '/groups/$letter': typeof GroupsLetterRoute
  '/history_/$year': typeof HistoryYearRoute
  '/match/$id': typeof MatchIdRoute
  '/news/read': typeof NewsReadRoute
  '/stadiums_/$slug': typeof StadiumsSlugRoute
  '/teams/$code': typeof TeamsCodeRoute
  '/api/public/track-visit': typeof ApiPublicTrackVisitRoute
  '/api/public/hooks/sync-live': typeof ApiPublicHooksSyncLiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fixtures'
    | '/groups'
    | '/history'
    | '/knockout'
    | '/live'
    | '/news'
    | '/players'
    | '/records'
    | '/search'
    | '/simulator'
    | '/stadiums'
    | '/statistics-data'
    | '/teams'
    | '/groups/$letter'
    | '/history/$year'
    | '/match/$id'
    | '/news/read'
    | '/stadiums/$slug'
    | '/teams/$code'
    | '/api/public/track-visit'
    | '/api/public/hooks/sync-live'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fixtures'
    | '/groups'
    | '/history'
    | '/knockout'
    | '/live'
    | '/news'
    | '/players'
    | '/records'
    | '/search'
    | '/simulator'
    | '/stadiums'
    | '/statistics-data'
    | '/teams'
    | '/groups/$letter'
    | '/history/$year'
    | '/match/$id'
    | '/news/read'
    | '/stadiums/$slug'
    | '/teams/$code'
    | '/api/public/track-visit'
    | '/api/public/hooks/sync-live'
  id:
    | '__root__'
    | '/'
    | '/fixtures'
    | '/groups'
    | '/history'
    | '/knockout'
    | '/live'
    | '/news'
    | '/players'
    | '/records'
    | '/search'
    | '/simulator'
    | '/stadiums'
    | '/statistics-data'
    | '/teams'
    | '/groups/$letter'
    | '/history_/$year'
    | '/match/$id'
    | '/news/read'
    | '/stadiums_/$slug'
    | '/teams/$code'
    | '/api/public/track-visit'
    | '/api/public/hooks/sync-live'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FixturesRoute: typeof FixturesRoute
  GroupsRoute: typeof GroupsRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  KnockoutRoute: typeof KnockoutRoute
  LiveRoute: typeof LiveRoute
  NewsRoute: typeof NewsRouteWithChildren
  PlayersRoute: typeof PlayersRoute
  RecordsRoute: typeof RecordsRoute
  SearchRoute: typeof SearchRoute
  SimulatorRoute: typeof SimulatorRoute
  StadiumsRoute: typeof StadiumsRoute
  StatisticsDataRoute: typeof StatisticsDataRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  HistoryYearRoute: typeof HistoryYearRoute
  MatchIdRoute: typeof MatchIdRoute
  StadiumsSlugRoute: typeof StadiumsSlugRoute
  ApiPublicTrackVisitRoute: typeof ApiPublicTrackVisitRoute
  ApiPublicHooksSyncLiveRoute: typeof ApiPublicHooksSyncLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics-data': {
      id: '/statistics-data'
      path: '/statistics-data'
      fullPath: '/statistics-data'
      preLoaderRoute: typeof StatisticsDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stadiums': {
      id: '/stadiums'
      path: '/stadiums'
      fullPath: '/stadiums'
      preLoaderRoute: typeof StadiumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knockout': {
      id: '/knockout'
      path: '/knockout'
      fullPath: '/knockout'
      preLoaderRoute: typeof KnockoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fixtures': {
      id: '/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof FixturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$code': {
      id: '/teams/$code'
      path: '/$code'
      fullPath: '/teams/$code'
      preLoaderRoute: typeof TeamsCodeRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/stadiums_/$slug': {
      id: '/stadiums_/$slug'
      path: '/stadiums/$slug'
      fullPath: '/stadiums/$slug'
      preLoaderRoute: typeof StadiumsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/read': {
      id: '/news/read'
      path: '/read'
      fullPath: '/news/read'
      preLoaderRoute: typeof NewsReadRouteImport
      parentRoute: typeof NewsRoute
    }
    '/match/$id': {
      id: '/match/$id'
      path: '/match/$id'
      fullPath: '/match/$id'
      preLoaderRoute: typeof MatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history_/$year': {
      id: '/history_/$year'
      path: '/history/$year'
      fullPath: '/history/$year'
      preLoaderRoute: typeof HistoryYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$letter': {
      id: '/groups/$letter'
      path: '/$letter'
      fullPath: '/groups/$letter'
      preLoaderRoute: typeof GroupsLetterRouteImport
      parentRoute: typeof GroupsRoute
    }
    '/api/public/track-visit': {
      id: '/api/public/track-visit'
      path: '/api/public/track-visit'
      fullPath: '/api/public/track-visit'
      preLoaderRoute: typeof ApiPublicTrackVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-live': {
      id: '/api/public/hooks/sync-live'
      path: '/api/public/hooks/sync-live'
      fullPath: '/api/public/hooks/sync-live'
      preLoaderRoute: typeof ApiPublicHooksSyncLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface GroupsRouteChildren {
  GroupsLetterRoute: typeof GroupsLetterRoute
}

const GroupsRouteChildren: GroupsRouteChildren = {
  GroupsLetterRoute: GroupsLetterRoute,
}

const GroupsRouteWithChildren =
  GroupsRoute._addFileChildren(GroupsRouteChildren)

interface NewsRouteChildren {
  NewsReadRoute: typeof NewsReadRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsReadRoute: NewsReadRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

interface TeamsRouteChildren {
  TeamsCodeRoute: typeof TeamsCodeRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsCodeRoute: TeamsCodeRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FixturesRoute: FixturesRoute,
  GroupsRoute: GroupsRouteWithChildren,
  HistoryRoute: HistoryRoute,
  KnockoutRoute: KnockoutRoute,
  LiveRoute: LiveRoute,
  NewsRoute: NewsRouteWithChildren,
  PlayersRoute: PlayersRoute,
  RecordsRoute: RecordsRoute,
  SearchRoute: SearchRoute,
  SimulatorRoute: SimulatorRoute,
  StadiumsRoute: StadiumsRoute,
  StatisticsDataRoute: StatisticsDataRoute,
  TeamsRoute: TeamsRouteWithChildren,
  HistoryYearRoute: HistoryYearRoute,
  MatchIdRoute: MatchIdRoute,
  StadiumsSlugRoute: StadiumsSlugRoute,
  ApiPublicTrackVisitRoute: ApiPublicTrackVisitRoute,
  ApiPublicHooksSyncLiveRoute: ApiPublicHooksSyncLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
